# Generated by Django 3.2.5 on 2021-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categories_category'),
        ('truffles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truffle',
            name='categories',
            field=models.ManyToManyField(related_name='truffles', to='categories.Category'),
        ),
    ]
