# Generated by Django 3.2.5 on 2021-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('truffles', '0002_truffle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='truffle',
            name='photos',
            field=models.ManyToManyField(related_name='truffles', to='images.Image'),
        ),
    ]
