# Generated by Django 3.2.5 on 2021-07-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truffles', '0005_auto_20210727_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truffle',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='truffle',
            name='quantity',
        ),
    ]
