# Generated by Django 3.2.5 on 2021-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truffles', '0006_auto_20210729_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='truffle',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truffle',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
