# Generated by Django 3.2.5 on 2021-07-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='longname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
