# Generated by Django 3.2.5 on 2021-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('categories', '0001_initial'),
        ('truffles', '0003_truffle_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truffle',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='truffles', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='truffle',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='truffles', to='images.Image'),
        ),
    ]
